version: "3"
services:
  postgres:
    image: custom/postgres:9.6
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3.0.7
    volumes:
      - redis-data:/data
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
  registry:
    image: registry:2
    ports:
      - '5000:5000'
  gitlab:
    image: 'custom/gitlab-ce:9.0.5'
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - '8080:8080'
      - '8181:8181'
      - '2224:22'
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-public:/var/opt/gitlab-public
    links:
      - postgres:postgres
      - redis:redis
      - smtp:smtp
      - registry:registry
    depends_on:
      - redis
      - postgres
      - smtp
      - registry
    env_file:
      - gitlab.env
  nginx:
    image: custom/nginx:1.11.13
    depends_on:
      - gitlab
    links:
      - gitlab:gitlab
    ports:
      - '8000:80'
    volumes:
      - gitlab-public:/var/opt/gitlab-public

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  gitlab-data:
    driver: local
  gitlab-public:
    driver: local
